
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE 
create user GUIA1 identified by GUIA1 default tablespace USERS temporary tablespace TEMP;
ALTER USER BDY1102_EP1 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_EP1;
GRANT "RESOURCE" TO BDY1102_EP1;
ALTER USER BDY1102_EP1 DEFAULT ROLE "RESOURCE";